version: '3.7'

services:
  maria_db:
    image: mariadb
    container_name: rpias-db
    ports:
      - 3360:3306
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - rpias_db:/var/lib/mysql
      - ./docker/rpias_server.sql:/docker-entrypoint-initdb.d/rpias_server.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

  rpias:
    image: chajr/php56-nginx-extended:latest
    container_name: rpias
    ports:
      - 8080:8080
    volumes:
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/rpias

volumes:
  rpias_db:
